VS Code Dev Container
astrandb/miele pull request #159
Opened 2022-11-28 16:38 UTC by juliekoubova

Hey, I created a VS Code devcontainer configuration using ludeeus' integration development container.

2022-11-29 17:20 UTC, astrandb requested changes
I have not used this dev container before so don't be offended if my comments are irrelevant.
- The .vscode folder should be included. It contains necessary launch files etc.
- The github actions that are included in the original dev container are missing here. I don't know if it is good or bad.

2022-11-29 17:20 UTC, astrandb commented on .devcontainer/.gitignore
> +secrets.yaml
Add a secrets.yaml file with dummy data in .devcontainer/

2022-11-29 17:20 UTC, astrandb commented on .github/workflows/cron.yaml
> +name: Cron actions
I pushed this file to this PR by mistake. It is present in the original dev container but i don't know if it is needed or not.

2022-11-29 17:20 UTC, astrandb commented on .github/workflows/pull.yml
> +name: Pull actions
I pushed this file to this PR by mistake. It is present in the original dev container but i don't know if it is needed or not.

2022-11-29 17:20 UTC, astrandb commented on .github/workflows/push.yml
> +name: Push actions
I pushed this file to this PR by mistake. It is present in the original dev container but i don't know if it is needed or not.

2022-11-29 17:20 UTC, astrandb commented on custom_components/miele/__init__.py
> -from .devcap import (  # noqa: F401
This change was pushed by me by mistake

2022-11-30 00:01 UTC, juliekoubova commented
You’re right, forgot the .vscode files by mistake. Will add them!

2022-12-11 13:42 UTC, astrandb commented
Thank you @juliekoubova  for the inspiration. A VS Code dev container is now set up.

2022-12-11 13:42 UTC, closed without merging