Read support for steam oven/microwave combination
astrandb/miele pull request #603
Opened 2024-12-15 11:51 UTC by DAccord

Adding read support for steam oven/microwave combination, i.e. Miele integration will now show correct program names when using the steam oven/microwave combination. Write support not included.
Tested with Miele DGM 7440.

2024-12-15 17:33 UTC, astrandb requested changes
Great job. Where did you find all these strings?
A handful of minor comments...

2024-12-15 17:33 UTC, astrandb commented on custom_components/miele/translations/en.json
> +          "heat_crockery": "Heat crockery",
Duplicate
```suggestion
```

2024-12-15 17:33 UTC, astrandb commented on custom_components/miele/translations/en.json
> +          "codfish_piece": "Codfish (piece)",
Duplicate
```suggestion
```

2024-12-15 17:33 UTC, astrandb commented on custom_components/miele/translations/en.json
> +          "codfish_fillet": "Codfish (fillet)",
Duplicate
```suggestion
```

2024-12-15 17:33 UTC, astrandb commented on custom_components/miele/translations/en.json
> +          "risotto": "Risotto",
Duplicate
```suggestion
```

2024-12-15 17:33 UTC, astrandb commented on custom_components/miele/translations/en.json
> +          "silverside_7.5_cm": "Silverside (7.5 cm)",
No period in key
```suggestion
          "silverside_7_5_cm": "Silverside (7.5 cm)",
```

2024-12-15 18:11 UTC, DAccord commented
Took me a 2-3 afternoons to try out all the programs on my DGM 7440 and record the IDs and corresponding names.

2024-12-16 09:42 UTC, astrandb requested changes
Just a little one left.
Note that en.json will be sorted in alphabetic order when up/downloaded to Lokalise.

2024-12-16 09:42 UTC, astrandb commented on custom_components/miele/translations/en.json
> -          "risotto": "Risotto",
One risotto should be retained.

2024-12-16 19:18 UTC, DAccord commented on custom_components/miele/translations/en.json
> -          "risotto": "Risotto",
Not sure why this got lost ...

2024-12-16 19:31 UTC, astrandb commented
Thank you @DAccord

2024-12-16 19:31 UTC, astrandb approved these changes

2024-12-16 19:32 UTC, merged